fix: Use frappe.db.get_single_value instead of frappe.get_single_value
Throwing builtins.AttributeError: module 'frappe' has no attribute 'get_single_value'
in old frappe version